# Generated by Django 6.0.3 on 2026-05-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='average_rating',
        ),
    ]
