# Generated by Django 6.0.3 on 2026-05-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
